# -*- coding: utf-8 -*-
"""EDA_LEAF.Ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x4pRHoziqf38Q5QWrXu5r_6madUKq2Of

# **INTRO**

As an initial step in the project, we conducted a focused exploratory data analysis of the LEAF prompt dataset in order to understand its structure, quality, and semantic characteristics before making any embedding-related design choices. The dataset contains 20,000 records and 20 fields, with no missing values, which makes it suitable for a robust semantic retrieval pipeline. Our analysis examined the distribution of languages, categories, subcategories, difficulty levels, text lengths, placeholders, and tags, as well as the distinction between semantic fields and metadata. This preliminary stage was essential to ensure that the embedding strategy would be grounded in the actual properties of the corpus rather than selected arbitrarily.
"""

import json
import pandas as pd
import numpy as np
from collections import Counter
import re

INPUT_FILE = r"C:/Users/TvCom/Downloads/LEAF-promptkaban-dataset/dataset.json"

with open(INPUT_FILE, "r", encoding="utf-8") as f:
    data = json.load(f)

print("Total records:", len(data))
print("Data structure type:", type(data))
print("First record keys:", list(data[0].keys()))

##Dataset overview
df = pd.DataFrame(data)
print("Dataset shape:", df.shape)
df.head(3)
print("DATA TYPES:")
print(df.dtypes)
print()

print("MISSING VALUES:")
print(df.isna().sum().sort_values(ascending=False))

"""**Dataset overview**

The dataset contains **20,000 prompt records** and **20 fields**.

The absence of missing values across all columns is particularly valuable, as it removes the need for imputation or record filtering before the embedding stage.
"""

#Core distributions for embeddings

print("LANGUAGE DISTRIBUTION:")
print(df["language"].value_counts())
print()

print("TOP 20 CATEGORIES:")
print(df["category"].value_counts().head(20))
print()

print("TOP 20 SUBCATEGORIES:")
print(df["subcategory"].value_counts().head(20))
print()

print("DIFFICULTY DISTRIBUTION:")
print(df["difficulty"].value_counts())
print()

print("HAS_PLACEHOLDERS DISTRIBUTION:")
print(df["has_placeholders"].value_counts())

"""**Core distributions for embeddings**

**Language distribution**

The corpus is overwhelmingly **English-dominant** *(19,991 out of 20,000 records)*. This strongly supports the use of an English-focused embedding model.

**Category distribution**

The category distribution reveals a broad thematic spread, with strong concentration in domains such as creative writing, marketing, sales, legal, and customer support.

**Subcategory distribution**

Subcategories appear more fine-grained and operationally informative than top-level categories. Labels such as ticket-responses, contract-drafting, cold-outreach, and plot-structure suggest that the dataset is not only topically diverse but also organized around task intent, which may be beneficial for semantic disambiguation when prompts are short or underspecified.

**Difficulty distribution**

The dataset is centered around intermediate-level prompts, followed by beginner, advanced, and expert prompts. This indicates that the corpus mostly represents practical, applied requests rather than highly specialized expert-only prompts. For embeddings, this matters because semantic variation is likely driven more by task formulation and domain vocabulary than by technical depth alone.

**Placeholder distribution**

Most prompts **do not contain placeholders**, while a meaningful minority does. This suggests that placeholders are not universal enough to define the corpus, but they are common enough to deserve explicit consideration during preprocessing. The embedding pipeline should therefore remain robust to both fully specified prompts and reusable template-style prompt
"""

#Text length analysis

df["title_len_chars"] = df["title"].fillna("").astype(str).str.len()
df["content_len_chars"] = df["content"].fillna("").astype(str).str.len()

df["title_len_words"] = df["title"].fillna("").astype(str).str.split().str.len()
df["content_len_words"] = df["content"].fillna("").astype(str).str.split().str.len()

print("TEXT LENGTH STATS:")
print(df[[
    "title_len_chars", "content_len_chars",
    "title_len_words", "content_len_words"
]].describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.95, 0.99]))

"""

The length statistics show a clear asymmetry between the two main textual fields: ***titles are generally short***, while **contents are** substantially **longer** and more informative. On average, **titles contain roughly 4.4 word**s, whereas **contents contain about 54.7 words**, with a long upper tail extending beyond 200 words. This confirms that content is the main carrier of semantic information, while title functions more as a compressed cue."""

#Title quality / noise check

def is_very_short(text, threshold=4):
    return len(str(text).split()) <= threshold

def has_all_caps(text):
    s = str(text)
    letters = [c for c in s if c.isalpha()]
    if not letters:
        return False
    upper_ratio = sum(c.isupper() for c in letters) / len(letters)
    return upper_ratio > 0.7

def has_informal_style(text):
    s = str(text).lower()
    patterns = [
        r"\bidk\b", r"\bwats\b", r"\bpls\b", r"\bwut\b", r"\bim\b",
        r"\bcuz\b", r"\btho\b", r"\bgimme\b", r"\babt\b", r"\blol\b"
    ]
    return any(re.search(p, s) for p in patterns)

df["title_very_short"] = df["title"].apply(is_very_short)
df["title_all_caps_style"] = df["title"].apply(has_all_caps)
df["title_informal_style"] = df["title"].apply(has_informal_style)

print("TITLE NOISE CHECK:")
print("Very short titles (%):", round(df["title_very_short"].mean() * 100, 2))
print("All-caps style titles (%):", round(df["title_all_caps_style"].mean() * 100, 2))
print("Informal-style titles (%):", round(df["title_informal_style"].mean() * 100, 2))

"""

The title analysis indicates that a large share of titles are very short (over 64%), while all-caps and strongly informal forms are present but much less frequent. This pattern suggests that titles cannot be assumed to be consistently descriptive."""

#Placeholder analysis

df["n_placeholders"] = df["placeholders"].apply(lambda x: len(x) if isinstance(x, list) else 0)

print("PLACEHOLDER STATS:")
print(df["n_placeholders"].describe())
print()

all_placeholders = Counter()
for row in df["placeholders"]:
    if isinstance(row, list):
        all_placeholders.update(row)

print("TOP 30 PLACEHOLDERS:")
for ph, cnt in all_placeholders.most_common(30):
    print(f"{ph}: {cnt}")

"""The placeholder statistics show that the median prompt contains no placeholders, but the maximum reaches 10, confirming that some prompts are highly templated. This means placeholders may preserve useful structural intent, especially in reusable business and professional prompts. Their treatment should therefore be cautious: removing them entirely could discard part of the prompt’s functional meaning."""

#Tag analysis

df["n_tags"] = df["tags"].apply(lambda x: len(x) if isinstance(x, list) else 0)

print("TAG COUNT STATS:")
print(df["n_tags"].describe())
print()

all_tags = Counter()
for row in df["tags"]:
    if isinstance(row, list):
        all_tags.update(row)

print("TOP 50 TAGS:")
for tag, cnt in all_tags.most_common(50):
    print(f"{tag}: {cnt}")

"""Tags are relatively dense and well populated, with a median of **4 tags per prompt** and an upper bound of 7. The most frequent tags indicate recurring themes such as **templates, compliance, documentation, analysis, email, Python, and marketing**. This suggests that tags provide concise semantic descriptors that may complement the main text, particularly when the prompt itself is brief or underspecified. At the same time, tags are editorial metadata, so their contribution should be validated empirically rather than assumed to improve retrieval by default."""

#Analysis of TOP 5 shortes and longest promts

print("5 SHORTEST PROMPTS BY WORD COUNT:")
shortest = df.sort_values("content_len_words").head(5)
for _, row in shortest.iterrows():
    print("\nID:", row["id"])
    print("Title:", row["title"])
    print("Content:", row["content"])
    print("Category:", row["category"], "| Subcategory:", row["subcategory"])


print("\n 5 LONGEST PROMPTS BY WORD COUNT:")
longest = df.sort_values("content_len_words", ascending=False).head(5)
for _, row in longest.iterrows():
    print("\nID:", row["id"])
    print("Title:", row["title"])
    print("Content preview:", row["content"][:1200])
    print("Category:", row["category"], "| Subcategory:", row["subcategory"])

"""**Shortest prompts by word count**

The shortest prompts illustrate a critical challenge for the embedding stage: some records contain extremely limited lexical information, such as one-word or near one-word requests. In these cases, semantic meaning is only partially expressed in the content field and is more likely to emerge from the combination of title, category, subcategory, and tags. These examples show why an embedding strategy based on content alone may underperform on a non-trivial subset of the datase

**Longest prompts by word count**

The longest prompts resemble full user problem descriptions rather than compact prompt templates. They contain narrative context, uncertainty, and implicit goals, which provide rich semantic material for dense representations. These cases are likely to benefit strongly from modern sentence-level or text-level embeddings, since the main challenge is not lexical sparsity but preserving topical and functional coherence across a longer sequence
"""

#Divios of semantic and semantic type of data

semantic_fields = [
    "title", "content", "category", "subcategory", "tags", "placeholders", "language"
]

metadata_fields = [
    "author_reputation", "version", "fork_count", "likes", "upvotes", "downvotes",
    "views", "uses", "created_at", "has_placeholders", "difficulty", "target_model"
]

print("SEMANTIC FIELDS:")
for c in semantic_fields:
    print("-", c)

print("\n METADATA / RANKING / FILTERING FIELDS:")
for c in metadata_fields:
    print("-", c)